version: "3.6"

services:
  db:
    container_name: "db"
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      # データの永続化
      - db:/var/lib/mysql
    tty: true
    env_file:
      - ./.env.sample
volumes:
  db:
