version: "3.6"

services:
  db:
    container_name: "db"
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      # 設定ファイルのマウント
      - ./db/conf.d:/etc/mysql/conf.d:cached
      # 初期データのマウント
      - ./db/initdb.d:/docker-entrypoint-initdb.d:cached
      # データの永続化
      - db-data-volume:/var/lib/mysql
    tty: true
    env_file:
      - ./.env.sample
volumes:
  db-data-volume:
